### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by VeraYeh** [VeraYeh/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML structure and add a race car image to the page.
- [x] Make a background color to cover entire page.
- [x] Make the race car sit on the top left corner of the page, and facing right by default.
- [x] Adjust the size of the race car to the right scale, leave some space for adding future feature to move the car around.
- [x] Review and test code again before submitting.
