### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by VeraYeh** [VeraYeh/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create CSS rules for rotation of the car.
- [x] Create an object to contain the rotation associated with each keydown event.
- [x] Create function to check which key is pressed and update the class of its expected rotation accordingly.
- [x] Test the function in the browser.
