### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by VeraYeh** [VeraYeh/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to the data model to hold the X and Y coordinates of the car on the page.
- [x] Add CSS rule to the image to make its position absolute.
- [x] Use the style property to change the car's top and left offset from the box.
- [x] Add a timer function to move the car a few pixels every 16 milliseconds.
- [x] Add a event listener to listen for user presses space key to start moving the car.
- [x] Test in the browser.
- [x] Review code again and delete unnecessary code.
