### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by VeraYeh** [VeraYeh/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a property with a boolean value to the data model to hold the status of the car (moving or not moving).
- [x] Update the space key event listener, switch the value of the car status property to the  opposite each time user presses space key.
- [x] Add another if statement to check the value of the car status property, set the interval timer to run the car if the value of the property is true, or clear the interval if the value is false.
- [x] Test in the browser, review code again and delete unnecessary code.
