### ISSUE TITLE
User can steer their car.

### ISSUE THREAD

**Issue by VeraYeh** [VeraYeh/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Define a function to make the car moving left at the same speed as current default(toward right).
- [x] Define a function to make the car moving up at the same speed as current default.
- [x] Define a function to make the car moving down at the same speed as current default.
- [x] Add conditions to keydown event listener to check which direction key is pressed when the car is moving.
- [x] If a direction key is pressed during car moving, clear the current timer and reset timer with the function for that direction.
- [x] Test in the browser, review code again and delete unnecessary code.
